# Data Science Jobs & Skill Frequencies in LA

In [7]:
#Packages
from bs4 import BeautifulSoup
import urllib
import re
import pandas as pd
import numpy as np
import requests
from urllib.request import urlopen
import matplotlib.pyplot as plt
import seaborn as sns
import itertools

In [8]:
#Set-Up
url = "https://www.indeed.com/m/jobs?q=data+scientist&l=los+angeles"
response = requests.get(url)

page = response.text
soup = BeautifulSoup(page, 'lxml')

all_matches = soup.find_all('a', attrs={'rel':['nofollow']})
for i in all_matches:
    print(i['href'])
    print(type(i['href']))
    print("https://www.indeed.com/m/" + i['href'])

viewjob?jk=de31f4e306948fb3
<class 'str'>
https://www.indeed.com/m/viewjob?jk=de31f4e306948fb3
viewjob?jk=1544ab41b4dc02b6
<class 'str'>
https://www.indeed.com/m/viewjob?jk=1544ab41b4dc02b6
viewjob?jk=d3b546ac10f53697
<class 'str'>
https://www.indeed.com/m/viewjob?jk=d3b546ac10f53697
viewjob?jk=f934053f9fe92002
<class 'str'>
https://www.indeed.com/m/viewjob?jk=f934053f9fe92002
viewjob?jk=fcb3275d1e7ef6f2
<class 'str'>
https://www.indeed.com/m/viewjob?jk=fcb3275d1e7ef6f2
viewjob?jk=0ee0ae6ba0ed34f5
<class 'str'>
https://www.indeed.com/m/viewjob?jk=0ee0ae6ba0ed34f5
viewjob?jk=9bf820e007c68714
<class 'str'>
https://www.indeed.com/m/viewjob?jk=9bf820e007c68714
viewjob?jk=f6576c3ba5851dbb
<class 'str'>
https://www.indeed.com/m/viewjob?jk=f6576c3ba5851dbb
viewjob?jk=614f9fbd6a80e036
<class 'str'>
https://www.indeed.com/m/viewjob?jk=614f9fbd6a80e036
viewjob?jk=273e5aca142e2619
<class 'str'>
https://www.indeed.com/m/viewjob?jk=273e5aca142e2619

In [9]:
title = []
company = []
location = []
jd = []
url = "https://www.indeed.com/m/jobs?q=data+scientist&l=Los+Angeles%2C+CA"
#url = "https://www.indeed.com/m/jobs?q=data+scientist&l=san+francisco"
for i in range(20):
    page = urlopen(url)
    soup = BeautifulSoup(page, 'lxml')
    all_matches = soup.findAll(attrs = {'rel':['nofollow']})
    
    for each in all_matches:
        jd_url = "https://www.indeed.com/m/"+each['href']
        response = requests.get(jd_url)
        jd_page = response.text
        jd_soup = BeautifulSoup(jd_page, 'html.parser')
        jd_desc = jd_soup.findAll('div', attrs = {'id':['desc']})
        
        title.append(jd_soup.body.p.b.font.text)
        company.append(jd_soup.body.p.span.previous_sibling[1:].split('-')[0])
        location.append(jd_soup.body.p.span.text)
        jd.append(jd_desc[0].text)
        
    url_all = soup.findAll(attrs = {'rel' : ['next']})
    #print(url_all)
    url = "https://www.indeed.com/m/"+str(url_all[0]['href'])

job = {'Title': title,
      'Company': company,
      'Location': location,
      'Job Description': jd}

df=pd.DataFrame.from_dict(job)
df.head(10)

,Title,Company,Location,Job Description
0,Data Scientist,Yoltaz,"Los Angeles, CA",We are looking for a Data Scientist to analyze...
1,Data Scientist,Deloitte,"Los Angeles, CA 90013",Deloitte Services LP includes internal support...
2,Data Scientist,Age of Learning,"Glendale, CA 91203",Company Overview:\nAge of Learning is a leadin...
3,Data Scientist,AvantStay,"Los Angeles, CA","Who we are...\nAvantStay delivers exceptional,..."
4,Lead Data Scientist,Yoltaz,"Los Angeles, CA",We are looking for a Lead Data Scientist to le...
5,Data Scientist,NBCUniversal,"Beverly Hills, CA","Fandango is seeking a driven, analytically cur..."
6,"Data Scientist, Marketing",Tinder,"West Hollywood, CA",Tinder brings people together. With tens of mi...
7,Data Scientist,GOAT,"Los Angeles, CA","With over 20 million members, GOAT is the worl..."
8,Data Scientist,"RMDS Lab, Inc","Pasadena, CA 91101",Data ScientistQualificationsMajor in quantitat...
9,Data Scientist/Visualization Master,Intermedia Advertising,"Los Angeles, CA 90067",We are seeking a Manager of Business Intellige...

In [17]:
#Reads through job description and returns 'True' or 'False' if specific keyword is present
df["C"] = df["Job Description"].str.contains(pat = r'\b[Cc]\s', regex=True)
df["C++"] = df["Job Description"].str.contains(pat = r'\b[Cc]\+(?=\W)', regex=True)
df["Java"] = df["Job Description"].str.contains("Java")
df["Javascript"] = df["Job Description"].str.contains("Javascript")
df["Python"] = df["Job Description"].str.contains("Python")
df["R"] = df["Job Description"].str.contains(pat = r'\b[R]\b', regex=True)
df["SQL"] = df["Job Description"].str.contains("SQL")
df["Hadoop"] = df["Job Description"].str.contains("Hadoop")
df["Hive"] = df["Job Description"].str.contains("Hive")
df["Pig"] = df["Job Description"].str.contains("Pig")
df["Spark"] = df["Job Description"].str.contains("Spark")
df["AWS"] = df["Job Description"].str.contains("AWS")
df["Tableau"] = df["Job Description"].str.contains("Tableau")

#If keyword is present (True), append into 'Required Skills'; if False, leave blank.   
df['Required Skills'] = np.where(df['C'] == True, "C, ", " ")
df['Required Skills'] = np.where(df['C++'] == True, df['Required Skills'] + "C++, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Java'] == True, df['Required Skills'] + "Java, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Javascript'] == True, df['Required Skills'] + "Javascript, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Python'] == True, df['Required Skills'] + "Python, ", df['Required Skills'])
df['Required Skills'] = np.where(df['R'] == True, df['Required Skills'] + "R, ", df['Required Skills'])
df['Required Skills'] = np.where(df['SQL'] == True, df['Required Skills'] + "SQL, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Hadoop'] == True, df['Required Skills'] + "Hadoop, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Hive'] == True, df['Required Skills'] + "Hive, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Pig'] == True, df['Required Skills'] + "Pig, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Spark'] == True, df['Required Skills'] + "Spark, ", df['Required Skills'])
df['Required Skills'] = np.where(df['AWS'] == True, df['Required Skills'] + "AWS, ", df['Required Skills'])
df['Required Skills'] = np.where(df['Tableau'] == True, df['Required Skills'] + "Tableau, ", df['Required Skills'])

#Counts the number of required skills in the job description
df['Number of Required Skills'] = df['Required Skills'].str.split().str.len()
df = df[['Title', 'Company', 'Location', 'Job Description', 'Required Skills', 'Number of Required Skills']]
df

,Title,Company,Location,Job Description,Required Skills,Number of Required Skills
0,2020 Artificial Intelligence/Machine Learning ...,Williams,"San Francisco, CA 94133",2020 Artificial Intelligence/Machine Learning ...,"Java, Python, R,",3
1,Data Scientist (Jr. to Sr. Level),Piper Companies,"San Francisco, CA 94107",Piper Companies is currently looking for Data ...,"Python, SQL,",2
2,Data Scientist,Gap Inc.,"San Francisco, CA",About Gap Inc.\nOur past is full of iconic mom...,,0
3,Measurement Data Scientist (SF),Pinterest,"San Francisco, CA 94103",Pinterest brings millions of people the inspir...,"Python, R, SQL, Hive,",4
4,Data Scientist,Blue Owl,"San Francisco, CA",A million people a year die in car collisions ...,"C, Python,",2
5,Data Scientist,University of California San Francisco,"San Francisco, CA",The Data Scientist will work with the Principa...,,0
6,Data Science and Strategy Extern,Impossible Foods,"Redwood City, CA",Do you want to be part of an exciting company ...,"Python, R,",2
7,Data Scientist,Deloitte,"San Francisco, CA",Deloitte Services LP includes internal support...,,0
8,"Data Scientist, Capital",Square,"San Francisco, CA 94103",Job Description\n\nAs a Data Scientist at Squa...,"Python, SQL, Hive,",3
9,Data Scientist,Loanpal,"San Francisco, CA",ABOUT LOANPAL\nWe are the world-positive lende...,,0
10,Data Science Analyst,Yelp,"San Francisco, CA 94102","At Yelp, it’s our mission to connect people wi...","Python, R, SQL, Tableau,",4
11,Engineering Manager - Health Machine Learning ...,Twitter,"San Francisco, CA 94103",ENGINEERING MANAGER - HEALTH MACHINE LEARNING ...,,0
12,Data Scientist,Asurion,"San Francisco, CA",Data Scientist-PRO01565\nDescription\n\nData S...,"Java, Python, R, SQL, Hadoop, Spark,",6
13,Applied Data Scientist,Yelp,"San Francisco, CA 94102",Yelp has hundreds of millions of pieces of use...,"Python, R, SQL, Spark,",4
14,Data Scientist,"Upstart Network, Inc.","San Mateo, CA",Upstart is the first lending platform to lever...,"Python, R,",2
15,Data Scientist,Wish,"San Francisco, CA 94103",Want to join our NEW centralized data science ...,"Python, R,",2
16,Data Scientist,AETNA,"San Francisco, CA",Description:\nResponsible for using statistica...,"Python, R, SQL,",3
17,2020 Information Technology - STAR Statistics ...,Federal Reserve Bank of San Francisco,"San Francisco, CA 94105",2020 Information Technology - STAR Statistics ...,,0
18,Data Scientist,Prosper,"San Francisco, CA 94104",Who We Are\n\nProsper is built on a simple ide...,"Python, R, SQL,",3
19,Data Scientist,States Title Holding,"San Francisco, CA",Create the model that transforms how real esta...,"SQL,",1
20,Data Scientist,Honor,"San Francisco, CA","Founded in 2015, Honor is now one of the faste...","Python,",1
21,Data Scientist - Rides,Uber,"San Francisco, CA 94103","At Uber, we ignite opportunity by setting the ...","Java, Python, R,",3
22,Principal Data Scientist,Catalyst,"San Francisco, CA 94107",Would you like to work with almost unlimited u...,"Java, Python, R,",3
23,Research Data Scientist,University of California San Francisco,"San Francisco, CA",The Research Data Scientist will join a collab...,,0
24,2020 Information Technology - Statistics and R...,Federal Reserve Bank of San Francisco,"San Francisco, CA 94105",2020 Information Technology - Statistics and R...,"Java, SQL,",2
25,Head of Data Science,Twitter,"San Francisco, CA 94103",Who We Are:\n\nData Science is the objective v...,,0
26,SENIOR DATA SCIENTIST,Under Armour,"San Francisco, CA",Under Armour is the chosen brand of this gener...,,0
27,DATA SCIENTIST,innovaccer,"San Francisco, CA 94105",Summary: We at Innovaccer are looking for a Da...,"SQL, Hadoop, AWS,",3
28,"Cloud Data Engineer, Revenue Science",Twitter,"San Francisco, CA 94103",Who We Are:\n\n\nAs data engineers in Revenue ...,"Java, Python, SQL, Hadoop, Hive, Pig, Spark,",7
29,"Junior Data Scientist, Predictive Modeling and...",Kaiser Permanente,"Oakland, CA",The Predictive Modeling team accelerates the u...,"Python, R, SQL, Tableau,",4
...,...,...,...,...,...,...
170,Data Scientist,Genentech,"South San Francisco, CA 94083",The Position\n\nThe Data Scientist of Technica...,"R, SQL,",2
171,"Data Scientist, Growth Data Science",Square,"San Francisco, CA 94103",Job Description\n\nAs a Data Scientist within ...,"Python, SQL,",2
172,Machine Learning Graphics Intern,Unity Technologies,"San Francisco, CA 94107",Our Machine Learning Graphics team wants to re...,,0
173,Senior Data Analyst,Publicis Sapient,"San Francisco, CA",The Publicis Sapient Data group is responsible...,"SQL,",1
174,"Senior Data Scientist, Lead",Eskalera Inc.,"San Francisco, CA","Join our team @ Eskalera!At Eskalera, our ulti...","Python, R,",2
175,Visualization & Data Engineer,Samsara,"San Francisco, CA","About Samsara\n-------------\n\nSamsara, found...","Python, SQL, Tableau,",3
176,"AI, Data Science Staffing, Recruiter Services ...",Xen.ai,"San Francisco Bay Area, CA","About the companyXen.AI, is an Artificial Inte...","R,",1
177,Computer Vision / Deep Learning Researcher,Hyprsense,"Burlingame, CA",Description\n\nWe’re looking for a talented re...,"C++,",1
178,Data Scientist - Customer Analytics,Walmart,"San Bruno, CA 94066",Position Description\nOur Customer Science org...,"Python, R, SQL, Hadoop, Hive, Spark, Tableau,",7
179,Data Scientist,Juvo,"San Francisco, CA",Juvo was founded with an overarching mission: ...,"Java, Python, R, Hadoop, Hive, Spark, AWS,",7
180,Sr. Data Scientist 1274618BR,Walmart,"San Bruno, CA 94066",Position Description\nWe are looking for passi...,"C++, Python, R, SQL, Hadoop, Hive, Spark,",7
181,Senior Data Analyst,MatchPointe Group,"San Francisco, CA","Senior Data AnalystFull-TimeSan Francisco, CAA...","Python, R, SQL, AWS, Tableau,",5
182,Data Science and Strategy Extern,Impossible Foods,"Redwood City, CA",Do you want to be part of an exciting company ...,"Python, R,",2
183,Data Science-Lead,Wipro Limited,"San Francisco, CA",Job Description\n\nKey skills required for the...,"Python,",1
184,Principal Data Scientist,Clarivate Analytics,"San Francisco, CA 94111",Clarivate Analytics is a global leader in prov...,"Java, Python, R,",3
185,Data Scientist - San Francisco,Bind Benefits,"San Francisco, CA 94111",Bind is a health technology and services compa...,"Java, Python, R, SQL, Hadoop, Hive, Spark, AWS,",8
186,Data Scientist,Coinbase,"San Francisco, CA 94111",Coinbase has built the world's leading complia...,"Java, Python, R, SQL, Spark, Tableau,",6
187,Data Scientist,Avani Technology Solutions Inc,"San Francisco, CA",Job Details\nJob Code\nJPSC-6409\nPosted Date\...,"Java, Python, R, SQL, Spark, AWS,",6
188,Clinical Data Scientist,BioMarin,"San Rafael, CA",BioMarin is the world leader in delivering the...,,0
189,Data Scientist - Grid Analytics,Sentient Energy Inc.,"Burlingame, CA 94010",Description:\nSentient Energy is looking for a...,"Python,",1
190,"Research Scientist, Deep Learning Intern (Fall...",Clarifai,"San Francisco, CA",About the Company\n-----------------\n\nClarif...,,0
191,Geospatial Data Scientist,Ceres Imaging,"Oakland, CA",About Us:\nCeres Imaging is a venture-backed c...,,0
192,Game Industry Data Scientist,GreenPark Sports,"Burlingame, CA",----------------------------\n\nDescription\n\...,"R, SQL, Tableau,",3
193,Data Scientist,CipherTrace,"San Francisco Bay Area, CA","South San Francisco Bay, California\nRequireme...","Python, Spark,",2
194,Data Science Product Owner,automotiveMastermind Inc.,"San Francisco, CA",***********\n\nWho we are:\n***********\n\naut...,,0
195,2020 Information Technology - Statistics and R...,Federal Reserve Bank of San Francisco,"San Francisco, CA 94105",2020 Information Technology - Statistics and R...,"Java, SQL,",2
196,Senior Data Scientist,Metis,"San Francisco, CA 94105",SENIOR DATA SCIENTISTWe are looking for Senior...,,0
197,"Data Scientist, Meta",Chan Zuckerberg Initiative,"Redwood City, CA",Founded by Dr. Priscilla Chan and Mark Zuckerb...,"Python, R, SQL,",3
198,Data Scientist,Oracle,"Redwood City, CA 94065",Data Scientist-19001AT1\n\n\nPreferred Qualifi...,"C++, Java, Python, R,",4
199,Data Scientist,Science 37,"San Francisco, CA",Science 37 is accelerating the research and de...,"Java, Javascript, Python, R, SQL, AWS, Tableau,",7

Skill Frequencies in Los Angeles

In [11]:
#Counts frequencies of keywords in the dataframe
df['Required Skills'].str.split(expand=True).stack().value_counts()

Python,        137
SQL,           110
R,             108
Tableau,        45
Java,           44
Spark,          41
AWS,            33
C++,            32
Hadoop,         32
Hive,           14
Pig,             4
Javascript,      1
C,               1
dtype: int64

# Data Scientist Job Reviews

In [15]:
company_name = []
reviewer = []
review_title = []
review_date = []
review_rating = []
review_description = []
review_pros = []
review_cons = []
review = []
pros = []
cons = []

url = "https://www.indeed.com/cmp?q=Data+Scientist%2FData+Analyst&l=Los+Angeles%2C+CA&from=discovery-cmp-search"
response = requests.get(url)
page = response.text
soup = BeautifulSoup(page, "html.parser")
all_matches = soup.findAll('a', attrs = {'itemprop':['name'], 'class':['cmp-CompanyWidget-name']})

#Diving into each of the job links
for a in all_matches:
    j_url = "https://www.indeed.com"+a['href']
    response_1 = requests.get(j_url)
    j_page = response_1.text
    j_soup = BeautifulSoup(j_page, 'html.parser')
    all_matches_2 = j_soup.find_all('a', attrs={'data-tn-element':['reviews-tab'],'class':["cmp-MenuItem-link cmp-u-noUnderline"]})
    
    for each in all_matches_2:
        r_url = "https://www.indeed.com"+each['href']
        for i in range(3):
            response_2 = requests.get(r_url)
            r_page = response_2.text
            r_soup = BeautifulSoup(r_page, 'html.parser')

            '''Because of the adaptive page (i.e. class name changing randomly like 'cmp-CompanyName' and 'cmp-company-name') 
            we write if statements so we do not append any 'blanks' into our list.'''
            
            #Extracting the title of the Company
            c_title_2 = r_soup.findAll('div', attrs = {'class':['cmp-CompanyName'], 'itemprop':['name']})
            if c_title_2 == []:
                c_title_2 = r_soup.findAll('div', attrs = {'class':['cmp-company-name'], 'itemprop':['name']})
            company_name.append([x.text for x in c_title_2])

            #Extracting the Name of the Reviewer for the review
            r_container_2 = r_soup.findAll('span', attrs = {'class':['cmp-reviewer']})
            if r_container_2 == []:
                r_container_2 = r_soup.findAll('span', attrs={'class':['cmp-ReviewAuthor'],'itemprop':['author']})
            reviewer.append([y.text for y in r_container_2])

            #Extracting the Name of the Reviewer for the review
            r_date = r_soup.findAll('span',attrs={'class':['cmp-review-date-created']})
            if r_date!=[]:
                r_date=[x.text for x in r_date]
            if r_date==[]:
                r_date= r_soup.findAll('span',attrs={'class':['cmp-ReviewAuthor'],'itemprop':['author'],'itemtype':['http://schema.org/Person']})
                r_date=[y.text for y in r_date]
                for x in range(len(r_date)):
                    element=r_date[x].split('-')[-1]
                    r_date[x]=element
            review_date.append(r_date)

            #Extracting the Title for the review
            r_title = r_soup.findAll('div', attrs = {'class':['cmp-review-title']})
            if r_title == []:
                r_title = r_soup.findAll('div', attrs = {'class':['cmp-Review-title']})
            review_title.append([y.text for y in r_title])

            #Extracting the Rating for the review
            r_rating = r_soup.findAll('div', attrs = {'class':['cmp-ratingNumber']})
            if r_rating == []:
                r_rating = r_soup.findAll('div', attrs = {'class':['cmp-ReviewRating-text']})
            review_rating.append([y.text for y in r_rating])

            #Extracting the Description for the review
            r_desc = r_soup.findAll('div', attrs = {'class':['cmp-review-content-container']})
            if r_desc != []:            
                rpc = [x.text for x in r_desc]
                review_description = [None] * len(rpc)
                review_pros = [None] * len(rpc)
                review_cons = [None] * len(rpc)

                for y in range(len(rpc)):
                    review_x = rpc[y].split('Pros')[0]                
                    review_description[y]=review_x

                    pros_x = rpc[y].split('Pros')[-1].split('Cons')[0]
                    if pros_x == review_x:
                        review_pros[y] = 'NA'
                    else:
                        review_pros[y] = pros_x

                    cons_x = rpc[y].split('Pros')[-1].split('Cons')[-1]
                    if cons_x == review_x:
                        review_cons[y] = 'NA'
                    else:
                        review_cons[y] = cons_x

            else:
                r_desc = r_soup.findAll('div', attrs = {'class':['cmp-Review-text'], 'data-tn-component':['reviewDescription']})
                rpc = [x.text for x in r_desc]
                review_description = [None] * len(rpc)
                review_pros = [None] * len(rpc)
                review_cons = [None] * len(rpc)

                for y in range(len(rpc)):
                    pros_x = rpc[y].split('Pros')[-1].split('Cons')[0]
                    cons_x = rpc[y].split('Pros')[-1].split('Cons')[-1]
                    review_x = rpc[y].split('Pros')[0]

                    review_description[y]=review_x

                    if pros_x == review_x:
                        review_pros[y] = "NA"
                    else:
                        review_pros[y] = pros_x

                    if cons_x == review_x:
                        review_cons[y] = "NA"
                    else:
                        review_cons[y] = cons_x

            review.append(review_description)
            pros.append(review_pros)
            cons.append(review_cons)

            j_next = r_soup.findAll(attrs = {'rel':['next']})
            if j_next == []:
                #print('This Company does not contain more than 1 page of reviews')
                break
            else:
                if str(j_next[0]['href'])[0:4] == 'http':
                    r_url = str(j_next[0]['href'])
                else:
                    r_url = "https://www.indeed.com/"+str(j_next[0]['href'])
                #print(r_url)

In [16]:
data = pd.DataFrame.from_dict({'company': company_name,
        'reviewer': reviewer,
        'review_title': review_title,
        'ratings': review_rating,
        'date': review_date,
        'descr': review,
        'pros': pros,
        'cons': cons
        })

C = []
R = []
RT = []
RR = []
RDTE = []
RDESC = []
RP = []
RC = []

for _, row in data.iterrows():
    com = row.company[0]
    for a in row.reviewer:
        C.append(com)
        R.append(a)
    for b in row.review_title:
        RT.append(b)
    for c in row.ratings:
        RR.append(c)
    for d in row.date:
        RDTE.append(d)
    for e in row.descr:
        RDESC.append(e)
    for f in row.pros:
        RP.append(f)
    for g in row.cons:
        RC.append(g)    
    
    
data_2 = pd.DataFrame({'Company': C,
                      'Reviewer': R,
                      'Review Title': RT,
                      'Review Ratings': RR,
                      'Review Date': RDTE,
                      'Review Content': RDESC,
                      'Pros': RP,
                      'Cons': RC})
data_2

,Company,Reviewer,Review Title,Review Ratings,Review Date,Review Content,Pros,Cons
0,Veritone,Hopefully not randomly laid-off soon,"Has potential, but job stability is always in ...",3.0,"January 7, 2018",Too many parts moving at the same time with un...,Cool new industry,Random unexplained lay-offs
1,Veritone,Software Engineer,"Great people, but planning leaves something to...",3.0,"June 24, 2019",- Relaxed work hours where most managers don't...,NA,NA
2,Veritone,Data Scientist Intern,Good company with creative atomsphere,5.0,"January 2, 2019",A company offers good atmosphere at creative t...,NA,NA
3,Veritone,Director New Business Development,Start up company with amazing AI promise,3.0,"October 2, 2017",Great AI resources coming out of this soon to ...,Cutting edge company,Start ups usual challenges
4,Hulu,Viewer Experience Advocate,It's okay,3.0,"October 25, 2019",I loved working here in the beginning. Once th...,NA,NA
5,Hulu,Marketing/Sales Ops,Was a model of a new kind of company but is no...,3.0,"October 19, 2019",In the beginning Hulu was a passion project ca...,"really work hard to keep things fun, holiday p...","managers from old world media, turned corporat..."
6,Hulu,"Data Science Manager, Advanced Analytics",Amazing Place to Work!,5.0,"October 4, 2019",Amazing place to work. Fast paced and interest...,NA,NA
7,Hulu,Digital Supply Chain Operations Specialist,"Environment filled with perks and fun, but not...",4.0,"October 1, 2019",Working at Hulu feels like living on a college...,"A lot of free food, good insurance",A lot of work with little advancement and comp...
8,Hulu,VXA,Can’t have a life.,5.0,"September 28, 2019","Don’t have kids, or go to school with this com...",NA,NA
9,Hulu,Broadcast Operations Technician,Innovative and stimulating place to work.,5.0,"September 25, 2019",Hulu is an incredible place to be employed. A...,Benefits,Salary is less than other places of equivalent...
10,Hulu,IT Help Desk Analyst,"Great company culture, fun place to work.",5.0,"September 13, 2019",Best place to work in LA for a few years runni...,NA,NA
11,Hulu,Viewer Experience Associate,Great place to work if you are entitled,1.0,"September 10, 2019",When you first start it's awesome. Then once y...,NA,NA
12,Hulu,Virtual experience advocate,Could wear what you want.,4.0,"August 14, 2019",you could wear most of the clothing without be...,NA,NA
13,Hulu,Broadcast Operations Intern,Working in Broadcast Operations is Enjoyable,4.0,"July 28, 2019","I performed my work as well as I could, and co...",NA,NA
14,Hulu,Customer Service Representative,Place sucks,1.0,"July 26, 2019",Was let go even though I was hitying all the s...,Nothing,Everything
15,Hulu,Viewer Experience Advocate,Proceed with caution,2.0,"June 15, 2019",The biggest perk is free hulu. Full of the bel...,NA,NA
16,Hulu,Manager,Great place to work,4.0,"June 14, 2019","It's a great culture, but the pay doesn't refl...",NA,NA
17,Hulu,Viewer experience advocate,Productive fun place to work,4.0,"May 18, 2019",Hulu is a great place to work. They trust you ...,"Breakfast, fridges, microwaves, full kitchen","Location for me, hotel seating"
18,Hulu,Viewer Experience Advocate,Management and this place is a joke,1.0,"May 16, 2019",Management and this place is a joke. It’s all ...,Nothing,Where do I start
19,Hulu,Viewer Experience Advocate,Hulu is the greatest,5.0,"March 25, 2019",I absolutely loved working at Hulu and will al...,NA,NA
20,Hulu,Customer Service Representative,"Fun work place, productive, etc.",4.0,"March 14, 2019",Job was okay overall and supervisors were cool...,"Good pay, decent hours, easy job",Not very organized with schedules/shifts
21,Hulu,Network Operations Engineer,Excellent company to work for,5.0,"March 12, 2019",Hulu is a forward thinking excellent technolo...,NA,NA
22,Hulu,vxa,Its is not a hard job,3.0,"February 28, 2019",Just like any call center in san antonio. you ...,Many benefits and pretty okay pay,Very poor communication and transparency altho...
23,Hulu,Team Manger,n/a,5.0,"February 2, 2019",I have nothing but good things to say about Hu...,NA,NA
24,Hulu,Viewer Experience Advocate,"Great Company, Not so great office culture",2.0,"January 29, 2019","I have tried hard to like this place, but the ...","Free Hulu, Free coffee, $10 weekly snack stipe...",Not enough transparency. Not many opportunitie...
25,Hulu,Viewer Experience Advocate,It's okay,3.0,"October 25, 2019",I loved working here in the beginning. Once th...,NA,NA
26,Hulu,Viewer Experience Advocate,Productive and fast paced work environment.,4.0,"January 23, 2019",Productive and fast paced work environment but...,NA,NA
27,Hulu,Viewer experience advocate,Fake fake fake,1.0,"January 2, 2019",The company began with high expectations insid...,Free Hulu,"Management incompetence, strict attendance pol..."
28,Hulu,Customer Service Representative,Ever changing work environment,4.0,"December 30, 2018",I enjoyed the time I was employed with Hulu as...,Free Hulu,Was laid off
29,Hulu,Virtual Experience Advocate,Loved it,5.0,"December 28, 2018",Great collaborative environment. Had a blast w...,Free subscription,Mandatory OT
...,...,...,...,...,...,...,...,...
2253,Facebook,Recruiting Coordinator,Great co-workers in a mission driven company,5.0,"May 31, 2019",Great work environment. Very busy times balanc...,"food, benefits, salary, the perks!","food, benefits, salary, the perks!"
2254,Facebook,Foreman,"Free food, great team to work with.",4.0,"May 25, 2019","If your FTE life is good, but if your continge...",Free lunches,Quality and accuracy not top priority.
2255,Facebook,Babysitter/Nanny,Pretty good,3.0,"May 21, 2019",I love the kids I watch they are loving and ea...,Yes free,No breaks
2256,Facebook,Advertising Manager,most enjoyable part,4.0,"May 20, 2019",Work hours were very flexible. i could work wh...,"free lunches, good pay",None
2257,Facebook,Line Cook/Prep Cook,productive,3.0,"May 13, 2019",fast pace company in a very diverse environme...,NA,NA
2258,Facebook,Program Manager,Enjoy it if you can!,5.0,"May 4, 2019",Facebook is the perfect storm of noble intenti...,"Food is free, but it's a benefit on your w2","Socialism in business, nothing is yours, keep ..."
2259,Facebook,Intern Software Engineer (Former Employee) - M...,A great compnay,5.0,"October 13, 2017",This is a good place to work. A typical day ar...,NA,NA
2260,Facebook,Technical Sourcing Manager/Operations Manager ...,great place,4.0,"April 24, 2019","I was there very early on, and got to do some ...",NA,NA
2261,Facebook,Public Content Moderator (Former Employee) - M...,Different game when you're a contractor,5.0,"April 23, 2019",I worked as a public content moderator at Face...,NA,NA
2262,Facebook,Hardware EPM & Coordinator (Current Employee) ...,Great place to work,5.0,"April 16, 2019",By far the best place for my work style. I thr...,NA,NA
2263,Facebook,Project Manager (Current Employee) - Washingto...,Proud to work at Facebook,5.0,"April 5, 2019",Getting hired at Facebook has been the highlig...,NA,NA
2264,Facebook,"Analyst (Current Employee) - Austin, TX - Apri...",Great place to work,5.0,"April 5, 2019","Great place to work. Free breakfast, lunch, an...",NA,NA
2265,Facebook,Senior Process Executive (Former Employee) - A...,Great Culture and Work Environment,4.0,"April 1, 2019",Facebook offers a great work environment. Grea...,NA,NA
2266,Facebook,Senior Analyst - Network Services Procurement ...,Fun work environment,4.0,"March 19, 2019",Great place to work at and the people are grea...,NA,NA
2267,Facebook,Client Solutions Manager (Current Employee) - ...,Wonderful Company,4.0,"March 17, 2019",Facebook is a wonderful company to work for. T...,NA,NA
2268,Facebook,Project Manager (Former Employee) - Menlo Park...,Facebook,4.0,"March 3, 2019","The overall Facebook culture is great, the fle...",NA,NA
2269,Facebook,"Sourcer (Former Employee) - Menlo Park, CA - F...",Cool art scene,4.0,"February 22, 2019",One of my favorite things about Facebook was t...,NA,NA
2270,Facebook,Uniformed Security Specialist (Current Employe...,Working at Facebook,3.0,"February 21, 2019",Working at Facebook as a security gaurd was fu...,NA,NA
2271,Facebook,Valet Parking Attendant -Facebook (Former Empl...,Great opportunities,5.0,"February 17, 2019",Room for improvement \rLearned great social sk...,NA,NA
2272,Facebook,Internal Solutions Engineer (Former Employee) ...,Great place to work,5.0,"February 12, 2019",Company cares a great deal about their employe...,NA,NA
2273,Facebook,"contract employee (Former Employee) - Austin, ...",Loved working there,5.0,"February 11, 2019",Great place to work. Mostly friendly. Fast pac...,NA,NA
2274,Facebook,Enterprise Support Tech (Current Employee) - M...,Great place.,5.0,"February 11, 2019",The benefits for working at a company like thi...,NA,NA
2275,Facebook,HR Project Manager (Current Employee) - Menlo ...,Lesson Learned,1.0,"February 10, 2019","Relocated for this position, was not worth it,...",NA,NA
2276,Facebook,Data Research Analyst (Former Employee) - Menl...,Workplace culture on fleek,5.0,"February 8, 2019",I was floored by the sheer luck I seemed to ha...,NA,NA
2277,Facebook,"SMB Team Lead (Current Employee) - Austin, TX ...",Great Environment,5.0,"February 6, 2019",This is where I am currently at. This is a gre...,NA,NA
2278,Facebook,"Food Prep (Former Employee) - Menlo Park, CA -...",facebook,4.0,"January 31, 2019",I would come to work a hour late so i can get ...,NA,NA
2279,Facebook,Client Partner - Global Marketing Solutions (F...,Good place to work for,3.0,"January 30, 2019",Facebook is a great place to work for.\r While...,NA,NA
2280,Penn Schoen Berland,Surveyor,Fun work environment,4.0,"June 11, 2019",Typical day included calling out of state to d...,NA,NA
2281,Penn Schoen Berland,International Politics Intern,Pretty young and hip workplace,5.0,"August 5, 2015",Most of the people I worked with were younger ...,NA,NA
2282,Penn Schoen Berland,Operations Manager,Intelligent people passionate about research,3.0,"May 7, 2012","Interesting clients, fascinating findings are ...",great coworkers,compensation packages seemed low; no 401k plan